blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/SoftwareSchmied/ha-ambientika-ventilation/security/advisories/new
    about: Report vulnerabilities and sensitive data privately.
